### ISSUE TITLE
SKLearn Wrap Standard Scaler does not use `outputs` argument

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/d3m-experimenter#20]
```
Traceback (most recent call last):
  File "/d3m-experimenter/tests/test_pipeline_generator.py", line 24, in setUp
    generate_problems=True
  File "/d3m-experimenter/experimenter/experimenter.py", line 65, in __init__
    self.output_pipelines_to_mongodb()
  File "/d3m-experimenter/experimenter/experimenter.py", line 265, in output_pipelines_to_mongodb
    added_pipeline_sum += self.mongo_database.add_to_pipelines_mongo(pipe)
  File "/d3m-experimenter/experimenter/database_communication.py", line 132, in add_to_pipelines_mongo
    default=json_util.default))
  File "/usr/local/lib/python3.6/dist-packages/d3m/metadata/pipeline.py", line 1749, in from_json
    return cls.from_json_structure(description, resolver=resolver, strict_digest=strict_digest)
  File "/usr/local/lib/python3.6/dist-packages/d3m/metadata/pipeline.py", line 1834, in from_json_structure
    step = cls._get_step_class(step_description['type']).from_json_structure(step_description, resolver=resolver)
  File "/usr/local/lib/python3.6/dist-packages/d3m/metadata/pipeline.py", line 761, in from_json_structure
    step.add_argument(argument_name, argument_type, argument_description['data'])
  File "/usr/local/lib/python3.6/dist-packages/d3m/metadata/pipeline.py", line 528, in add_argument
    primitive=self.primitive,
d3m.exceptions.InvalidArgumentValueError: Unknown argument name 'outputs' for primitive d3m.primitives.data_preprocessing.standard_scaler.SKlearn.
```

**Comment by orionw** [comment]
Running `execute` or `all` will pull the pipelines from the database and run those.  Since those are the old pipelines, they will fail on the new docker.  When we clear the database of pipelines, it'll run normally again.
